services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  scraper:
    build: .
    container_name: scrapy_spider
    volumes:
      - .:/app
      - ./credentials:/app/credentials
      - ./logs:/app/logs
    env_file:
      - .env
    tty: true

volumes:
  db_data:
