version: '3'
services:
  splash:
    image: scrapinghub/splash
    ports:
      - "8050:8050"
    restart: always

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: songs_db
      MYSQL_USER: scrapy_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql

  scrapy:
    build: .
    depends_on:
      - splash
      - mysql
    links:
      - splash
      - mysql
    environment:
      - SPLASH_URL=http://splash:8050
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=songs_db
      - MYSQL_USER=scrapy_user
      - MYSQL_PASSWORD=password

volumes:
  mysql_data:
